import { 
     Button,
     TextField,
     Box,
     Typography,
     Grid,
     Container,
     Divider,
     Avatar,
     Stack,
     Link,
     IconButton,
     Icon,
     Collapse,
     Drawer,
     List,  
     ListItem,
     ListItemButton,
     ListItemIcon,
     ListItemText,
     ListItemAvatar,
     FormControl,
     InputLabel,
     Select,
     MenuItem,
     FormHelperText,
     Card,
     CardContent,
     CardActions,
     Snackbar,
     Table,
     TableBody,
     TableCell,
     TableContainer,
     TableHead,
     TableRow,
     Paper,
     TablePagination,
     TableSortLabel,
     Tooltip,
     AppBar,
     Toolbar,
     Dialog,
     DialogTitle,
     DialogContent,
     DialogActions,
     Alert,
     DialogContentText,
     CircularProgress,
     Backdrop,
     Menu,
     InputAdornment,
     Radio,
     RadioGroup,
     Checkbox,
    } from '@mui/material';

import MenuIcon from '@mui/icons-material/Menu';
import AddIcon from '@mui/icons-material/Add'
import CloseIcon from '@mui/icons-material/Close';
import EditIcon from '@mui/icons-material/Edit';
import DeleteIcon from '@mui/icons-material/Delete';
import FaceRetouchingNaturalIcon from '@mui/icons-material/FaceRetouchingNatural';
import SettingsOutlinedIcon from '@mui/icons-material/SettingsOutlined';
import AndroidOutlinedIcon from '@mui/icons-material/AndroidOutlined';
import LogoutOutlinedIcon from '@mui/icons-material/LogoutOutlined';
import VisibilityOffOutlinedIcon from '@mui/icons-material/VisibilityOffOutlined';
import VisibilityOutlinedIcon from '@mui/icons-material/VisibilityOutlined';
import AccountCircleOutlinedIcon from '@mui/icons-material/AccountCircleOutlined';
import SpaceDashboardOutlinedIcon from '@mui/icons-material/SpaceDashboardOutlined';
import PeopleOutlineOutlinedIcon from '@mui/icons-material/PeopleOutlineOutlined';
import Person2OutlinedIcon from '@mui/icons-material/Person2Outlined';
import AnalyticsOutlinedIcon from '@mui/icons-material/AnalyticsOutlined';
import NotificationsOutlinedIcon from '@mui/icons-material/NotificationsOutlined';
import TextsmsOutlinedIcon from '@mui/icons-material/TextsmsOutlined';
import FormControlLabel from '@mui/material/FormControlLabel';
import FormLabel from '@mui/material/FormLabel';
import PhishingIcon from '@mui/icons-material/Phishing';

const Mui={
     TextField,
     Button,
     Box,
     Container,
     Grid,
     Typography,
     Divider,
     Avatar,
     Stack,
     Link,
     IconButton,
     Icon,
     Collapse,
     Drawer,
     List,
     ListItem,
     ListItemButton,
     ListItemIcon,
     ListItemText,
     ListItemAvatar,
     FormControl,
     InputLabel,
     Select,
     MenuItem,
     FormHelperText,
     Card,
     CardContent,
     CardActions,
     Snackbar,
     Table,
     TableBody,
     TableCell,
     TableContainer,
     TableHead,
     TableRow,
     Paper,
     TablePagination,
     TableSortLabel,
     Tooltip,
     AppBar,
     Toolbar,
     MenuIcon,
     AddIcon,
     Dialog,
     DialogTitle,
     DialogContent,
     DialogActions,
     Alert,
     DialogContentText,
     CloseIcon,
     EditIcon,
     DeleteIcon,
     CircularProgress,
     Backdrop,
     Menu,
     FaceRetouchingNaturalIcon,
     SettingsOutlinedIcon,
     AndroidOutlinedIcon,
     LogoutOutlinedIcon,
     VisibilityOffOutlinedIcon,
     VisibilityOutlinedIcon,
     InputAdornment,
     AccountCircleOutlinedIcon, 
     SpaceDashboardOutlinedIcon,
     PeopleOutlineOutlinedIcon,
     Person2OutlinedIcon,
     AnalyticsOutlinedIcon,
     NotificationsOutlinedIcon,
     TextsmsOutlinedIcon,
     FormControlLabel,
     FormLabel,
     Radio,
     RadioGroup,
     PhishingIcon,
     Checkbox, 
}
export default Mui